### PR TITLE
make examples work with unicode inputs

### PR DESCRIPTION
**Pull request by mattbennett**
Addresses #349

### CODE REVIEW

**Comment by davidszotten** [comment]
i'm still on the fence about this. e.g. `u` prefix vs `unicode_literals`, or even just "assuming" py3

**Comment by mattbennett** [comment]
I am in favour of assuming py3. Seems fitting for an example to use the best version of the language.

I will rework these.

**Comment by mattbennett** [comment]
@davidszotten happy for this to land?

**Comment by davidszotten** [comment]
👍

**Pull request merged**
